spring.application.name=ChatBot MVT

spring.datasource.url=jdbc:mysql://localhost:3306/chatbot
spring.datasource.username=root
spring.datasource.password=7410056

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

access.token=EAA8Qn1gygQwBRZAgHDN1er42dz6nonybUYmQu7gAbSJKyyMM4C8WlUQVRF7h9qFJlbPnChVzgmUlLuFy7WG7HDfR01mzD0nj98syHOfcx1z5DxD0mukTzEOumZC79j4dIpISDixZCF0mZCJX2DtgM7ZB8hzZCFygXnRYsjr7vCSN1otE4QQ4syvZBNyt5ZCQFDYrrlZAmhAt3Kwt0lDQZAjxIIT9ZCl1oG1CRF5zRFSesRn96DjVCwmsFST03sYHrMYwsUhqZCvZAZCxbuq5j729CFzdvofQO1tVIguZC405DdH2wZDZD
whatsapp.phone-id=1098097890052276